name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set permissions
      run: chmod -R 777 .

    - name: Build with Docker
      # Мы используем прямой вызов команд, чтобы контейнер не путался
      run: |
        docker run --rm -v $(pwd):/home/user/hostcwd \
        -u $(id -u):$(id -g) \
        kivy/buildozer:latest \
        bash -c "buildozer android debug"

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: rbmk-simulator-apk
        path: bin/*.apk
        
